### ISSUE TITLE
Ontwerpen stap 4: Site-map

### ISSUE THREAD

**Issue by mcphendriks** [mcphendriks/team-performance-matters-optimized-website#6]

**Comment by mcphendriks** [comment]
@TessaViergever: Ik heb een sitemap gemaakt in Miro. De sitemap staat in hetzelfde  bestand als het teamcanvas. Je kunt zo nodig wijzigingen doen.

**Comment by TessaViergever** [comment]
@mcphendriks 

Ik heb een nieuwe sitemap gemaakt (paar kleine aanpassingen). Heb voor de zekerheid ook de URL + .ejs bestand erbij gezet.

Heb een issue ingeschoten + assigned aan jou om een plantDetail.ejs bestand te maken op main (denk ik? omdat je op de kaartjes op de index pagina kunt klikken en dan op een plant detail pagina komt toch? Als dit niet nodig is kun je m verwijderen natuurlijk!)

Verder wist ik niet wie/wat ging doen dus heb ook wat .ejs en url plekken leeg gelaten die nog ingevuld kunnen worden zodra de routes aangemaakt zijn. (:
